from datetime import date, datetime, timezone
from enum import StrEnum
from typing import List, Optional
from uuid import uuid4

from pydantic import AliasChoices, BaseModel, Field

from app.schemas.generic_types import TranslatedFields


class IssueType(StrEnum):
    PEST = "pest"
    DISEASE = "disease"
    NUTRIENT_DEFICIENCY = "nutrient_deficiency"
    WEED = "weed"
    ENVIRONMENTAL = "environmental"
    HEALTHY = "healthy"
    OTHER = "other"


class SeverityLevel(StrEnum):
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class CropDiagnosisInvariantFields(BaseModel):
    issue_type: IssueType = Field(
        default=IssueType.OTHER,
        description="Category of the detected issue, or HEALTHY if normal.",
    )
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score of the diagnosis between 0.0 and 1.0.",
    )
    severity: SeverityLevel = Field(
        default=SeverityLevel.MEDIUM,
        description="Assessed severity level of the issue.",
    )


class CropDiagnosisTranslatableFields(BaseModel):
    issue_name: str = Field(
        description="Identified common or technical name of the pest, disease, or condition."
    )
    symptoms: List[str] = Field(
        default_factory=list,
        description="Specific visible symptoms detected by the vision model.",
    )
    affected_parts: List[str] = Field(
        default_factory=list,
        description="Parts of the plant affected (e.g., leaves, stems, pods, roots).",
    )
    diagnosis_summary: str = Field(
        description="Agronomic explanation of the diagnosis and recommended management urgency."
    )


class CropDiagnosisResult(
    CropDiagnosisInvariantFields, CropDiagnosisTranslatableFields
):
    """
    Multimodal AI diagnostic result for an observation (resolved in user_language or english).
    """


TranslatedCropDiagnosisFields = TranslatedFields[CropDiagnosisTranslatableFields]


class CropDiagnosisDocument(
    CropDiagnosisInvariantFields, TranslatedCropDiagnosisFields
):
    """
    MongoDB document model for storing diagnosis with both English and user_language translations.
    """


class CropObservationCreate(BaseModel):
    """
    Payload for creating a new crop observation.
    """

    observation_date: Optional[date] = Field(
        default=None,
        description="Date of observation (defaults to current date if not provided).",
    )
    growth_stage: Optional[str] = Field(
        default=None,
        description="Observed growth stage (e.g., Vegetative, Flowering).",
    )
    image_file_ids: List[str] = Field(
        default_factory=list,
        description="File IDs of photos captured in the field (up to 4).",
    )
    audio_file_id: Optional[str] = Field(
        default=None,
        description="File ID of the recorded farmer voice note.",
    )
    notes: Optional[str] = Field(
        default=None,
        description="Farmer notes or voice note transcript.",
    )


class CropObservation(CropObservationCreate):
    """
    Represents a farmer's field observation log containing photos,
    voice notes, farmer notes, and AI diagnostic results.
    """

    id: str = Field(
        default_factory=lambda: uuid4().hex,
        description="Unique identifier of the crop observation.",
        validation_alias=AliasChoices("id", "_id"),
        serialization_alias="_id",
    )
    crop_id: str = Field(description="Associated cultivation crop ID.")
    farm_id: str = Field(description="Farm ID where the crop is cultivated.")
    user_id: str = Field(description="ID of the user who recorded the observation.")
    observation_date: date = Field(
        default_factory=date.today,
        description="Date when the field observation was recorded.",
    )
    audio_transcription: Optional[str] = Field(
        default=None,
        description="Transcribed text from the recorded voice note in the farmer's language.",
    )
    ai_diagnosis: Optional[CropDiagnosisResult] = Field(
        default=None,
        description="Multimodal pest/disease diagnosis result generated by Gemini.",
    )
    agricultural_input_recommendation_id: Optional[str] = Field(
        default=None,
        description="ID of the agricultural input remedy recommendation generated from this diagnosis.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the observation was created.",
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the observation was last updated.",
    )
